### PR TITLE
Fix lein resolution.

### PR DESCRIPTION
**Pull request by sebukoleth**
On my Windows box proto-repl was unable to resolve lein location. Giving the path to lein also did not help. This is because 'leinPath' was not being used. This change looks at leinPath, if non-empty and prepends it along with file separator - if needed.

### CODE REVIEW

**Comment by jasongilman** [comment]
Thanks for the pull request! I'll have a look with any feedback or merge it in the next couple days. I appreciate any fixes that make it work better on Windows.

**Comment by sebukoleth** [comment]
You are welcome. Although I do suspect that my problem was more to do with some corporate access restrictions in action on my Windows box. Running proto-repl on a Windows VM in my Linux box worked without this change.

**Comment by jasongilman** [comment]
I took a look at your code and added a few comments. Do you think this change is still necessary given that it's working for you? Do you think the original issue is still there? I'm trying to understand what the issue is but I don't think I get it yet.

I noticed that you said "'leinPath' was not being used" but it is used in the creation of the env that's passed to the spawn call.

**Comment by jasongilman** [comment]
Also another thing, I'm a bit new to the whole pull request process in open source. I'm used to reviewing code from people who are paid to write it so I'm a bit picky in my comments. I really appreciate the effort and time you've put in to help make this a better product. Thanks

**Comment by sebukoleth** [comment]
Although the filteredEnv did contain leinPath (verified by examining the variable), during execution on the plain Windows 7 box, it would keep raising error that path to lein must be set.

As I said this behaviour could have been due to the fact that the Atom instance was running on a corporate Windows machine that has very strict access controls set. It also has on-the-fly full disk encryption.

However, with the changes that explicitly pointed to the lein executable, proto-repl was able to successfully launch the nREPL.

Maybe it will be better to create a function that would get invoked if and only if the initial spawn that uses filteredEnv did not work. The explicit path-ed lein invoke would then go into that function.

**Comment by jasongilman** [comment]
I saw another person with the same problem on #13. I installed a windows VM, tested it and saw the issues they reported. I tried the fixes in this pull request but it didn't quite fix it. I rewrote it but based it on what was here. Everything should be working now. Even though this pull request didn't get merged it it was a big help in the actual solution used.

**Pull request closed without merging**
