### PR TITLE
Modified openFileContainingVar to work on all platforms.

### PR DESCRIPTION
**Pull request by didibus**
The Clojure openFileContainingVar script used to fail on Windows,
because it did not handle the path in a multiplatform safe way and it
was relying on the unzip external utility that does not exist on
Windows.

I changed the code to generate valid paths no matter what platform we're
running on by relying on Java's path manipulation constructs instead of
string concatenation.

I also modified the unziping of the Jar to be performed all in Clojure
instead of relying on an external tool.

These changes were made to fix the "proto-repl:open-file-containing-var"
command on Windows.

Issues Related:
- https://github.com/jasongilman/proto-repl/issues/172
- https://github.com/jasongilman/proto-repl/issues/217

### CODE REVIEW

**Comment by jasongilman** [comment]
Thanks for the pull request! The code looks good on my initial read through. I like the solution you've used. I'll want to do some testing before merging it.

**Comment by didibus** [comment]
Sounds good, FYI, I have only tested it on Windows 7.

**Comment by indiejames** [comment]
Jason,

Took a look at this since I stole this code from you earlier so my VS Code
extension suffers from the same bug. I'm confused about the code in the
pull request as it has a `loop-recur` inside a `let` binding. I thought
`recur` could only be called from a tail position. How is the `recur` on
line 718 in a tail position?

Thanks,

James

**Comment by indiejames** [comment]
Also,

On line 726 it looks like it is still using hard-coded forward slashes for
the temporary jar path: "/.lein/tmp-atom-jars/". I think this probably
creates a single directory with forward slashes in the name on Windows
instead of multiple directories, but I'm not sure. That probably doesn't
matter much, but it might be weird for the user to find that directory
lying around. I think in Java it's OK (idiomatic) to use strings to
construct paths by including the `File.separator` string between path
segments - at least it used to be; it's been a long time.

-James

**Comment by didibus** [comment]
@indiejames Hum, good catch on line 726. I missed that one. Not sure of the impact, but better be safe then sorry I guess. I'll fix it tomorow. The whole thing should be replaced with clojure.java.io/file. The clojure file can take a vararg of the folders in the path and it'll handle the proper separator for us.

As for the loop-recur, all that it means to be in a tail position is that it must be the last thing that can be done before exiting the function. So if you add a statement after the recur, it would stop being in tail position. In my case, the loop can exit at 3 places, when when-not is false, when if-not is true and when if-not if false. On the latter I recur just before exiting, and I do nothing else after, so it's at a tail end of an exit point.

**Comment by indiejames** [comment]
@didibus Thanks for the explanation, but I'm still confused about the `recur`. It's at the end of the the `let` binding for `file-path`, not at an exit point to the function - unless by 'function' you are referring to the `loop` expression. There is conditional logic after that and in any case you construct the return value using the value of the binding on line 742 with `[file-path line]`, which technically happens after the `recur`. Is it the case that the `recur` can happen at the end of a binding and this is treated the same as if it is at the exit point for a function? Or is it that the `recur` must simply be at an exit point for the `loop`?

**Comment by didibus** [comment]
@indiejames Yea by 'function' in this case I meant the loop s-expression. The exit point must be for the loop if using loop-recur or at the function if using recur with an fn.

**Comment by didibus** [comment]
@indiejames It's easy to understand if you understand what tail call optimization does under the hood. Basically a recursive loop normally has a stack, and all local state is pushed on the stack on the way down, and popped on the way up. If the next recursive call is at the exit point, meaning nothing after it will need to use local state, we don't need to remember those values, so it's safe to free their memory. This is tail call optimization. What recur does is it loops without a stack, therefore it never pushes anything to the stack, but it also cannot continue where it left off, because there is no stack to keep track of that.

Say we recurse 10 times, without recur, we'd have pushed 10 local states on the stack. But if on our way out the recursive chain, we don't have anything left to do, that's just wasted memory. Now if your recursion is exponential, you could quickly run out of memory. Clojure validates you're doing it correctly. So it'll check that the last thing to evaluate inside loop is a recur call, and it'll throw an exception if it's not.

Now if you wanted to remember something, so you can continue it, you would need to store that yourself, which is normally done by adding one more argument that you carry over as you loop.

**Comment by didibus** [comment]
@indiejames I've tested the code at line 726, and it works fine. I believe the File constructor can properly parse Windows, Mac or Linux paths, so it handles it correctly. I'll leave it as such unless someone actually reports a bug for this, as I'm pretty sure it is not an issue. I tested it on Windows, and I think @jasongilman tested it on Mac.

If it turns out to be a problem in your extension, here's what you can replace the s-expression with:

```
(clojure.java.io/file
    (System/getProperty "user.home")
    ".lein"
    "tmp-atom-jars"
    partial-jar-path)
```

**Pull request merged**
